### ISSUE TITLE
Welcome to iOS Application Development

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2016-Summer-Forum#1]
Hi class.  Please set your notifications appropriately so that you are updated on posts to this forum.  This is _the_ mechanism for all course communication.

**Comment by kbsrunschi** [comment]
Hello! Very excited for this class and to start building apps :) 

until I can figure out how to properly imbed The Oatmeal's images: http://theoatmeal.com/comics/selfie_stick

**Comment by jbairUChicago** [comment]
Hello!

Thanks,
Josh Bair

**Comment by benvcarr** [comment]
![how-do-you-do-fellow-kids](https://cloud.githubusercontent.com/assets/9138362/16216246/dd6357b0-372e-11e6-8400-892a72a99a5b.png)

**Comment by pikashoes** [comment]
Hi. Just some important safety tips:
![Image](http://67.media.tumblr.com/9de20eef1b488a4a35c197e5e4d01160/tumblr_nvo7z8oqxx1qk6kh5o1_500.jpg)

(Don't actually do this)

**Comment by naietsg** [comment]
Hello!

**Comment by tjp36** [comment]
Hello!  Posting my message as per homework instructions.

-Ted

**Comment by jdgarza** [comment]
Hi everyone!

**Comment by guofenzhao** [comment]
Visit Navy Pier if you are happy! 

Visit Navy Pier if you are sad!

Visit Navy Pier if you need fresh air

**Comment by hiesenburg88** [comment]
Hi everybody! Enjoy your weekends.
- Mark 
  ![](http://cdn.gadgetlove.com/media/products/2/799701442/799701442-original-47843594.gif)

**Comment by jvmakin** [comment]
Howdy.

**Comment by adlee-dev** [comment]
Hi everybody!

**Comment by fungedwin** [comment]
Hi everyone!
