### ISSUE TITLE
XCode github push issue

### ISSUE THREAD

**Issue by tjp36** [uchicago-mobi/2016-Summer-Forum#10]
Was anyone able to successfully push to their remote repository using XCode?  After entering the necessary information into Xcode, I selected source control > push.  A menu then appeared that had a "push local changes: " line of text and a drop down text box containing origin/master.  I selected push, which brought me to a new menu.  

The next menu reads "Enter your credentials for the repository (my repository) on host 'github.com'.  Strangely, the User Name field is greyed out for me and only contains the word "git".  I tried both authentication methods (SSH and the User Name and Password (i.e. https)), but both failed for me.  I know the password I am entering is correct.

Eventually I just gave up and successfully pushed via the command line so it isn't a huge deal exactly, but it would be nice to know exactly how to do this via Xcode itself without resorting to the terminal.

Ted

**Comment by guofenzhao** [comment]
I had similar problem with another course because clean up was needed. It only worked when I started afresh. Hopefully iOS is easier. Good luck

**Comment by susanstevens** [comment]
Do you have two-factor authentication enabled on your Github account?  If so, you need to use a personal access token (which you can generate on Github) and enter it instead of a password.

https://help.github.com/articles/https-cloning-errors/#provide-access-token-if-2fa-enabled

**Comment by tabinks** [comment]
@susanstevens has a good suggestion.  Although, to be honest, I've always had issues with connecting GitHub repos directly to Xcode to push.  I will use Xcode to make my commits, but then to push I will jump to the command line or GitHub Desktop app.

**Comment by adlee-dev** [comment]
So these are the steps I did, which seemed to work (with either HTTPS or SSH):
1. Create your project on your Mac, adding it to your local git repository (there's an "Options" button on the screen where you tell Xcode to save the project files which exposes the option to create a git repository).
2. Get the link for your remote repository on GitHub (for assignments, this comes from the GitHub Classroom thing; for other things make a new repository on your GitHub account and get the HTTPS/SSH link for that).
3. Add the remote repository to the Xcode project: Source Control >> [ProjectName] – [Branch] >> Configure [ProjectName]. Click on the "Remotes" tab, then on the "+" symbol at the bottom, choosing "Add Remote". Put in the name and address for the remote.
4. At this point, either push the (default) project files or make some changes and then commit and push.
5. Will then ask you for credentials. If using HTTPS remote, just use your GitHub username and password. For SSH, you would need to switch authentication from Username and Password to SSH Keys and either enter your passphrase or let the operating system do it for you by fetching it from the keychain. Xcode should then upload the push to GitHub.
