### ISSUE TITLE
Where are the final project requirements?

### ISSUE THREAD

**Issue by hiesenburg88** [uchicago-mobi/2016-Summer-Forum#101]
I'm having trouble finding the final project requirements that we went over in class. I believe it was lecture 7 or 8 where we went through all of the items that we're supposed to include in addition to the app. I've scanned through both decks and I don't see anything about the final project. Am I missing it? 

Thanks in advance.

**Comment by aietsg** [comment]
Check the end of [lecture 6](https://ff8276a3d76177159b643022d4cc86d3f633fc86.googledrive.com/host/0B3XzcKIiWyccdlgtOW42N0xQZjQ/MPCS51030/2016-Summer/Session6/MPCS51030-2016-Summer-Lecture6.pdf)

**Comment by hiesenburg88** [comment]
Thanks. For some reason I thought there was a more extensive writeup about the requirements. It looks like the only 2 requirements to the app are 1) a Settings screen and 2) a page on How to use the app

**Comment by susanstevens** [comment]
There are more requirements than those two!  The detailed requirements for the final projects are at the end of the Session 8 slides. For some reason the link for Session 8 slides on the class website is taking me to the slides for Session 7 (@tabinks). The correct link for Session 8 slides is in issue #90.

**Comment by benvcarr** [comment]
For posterity, here are the requirements from the slides so everyone doesn't have to go find them every time:

FINAL PROJECT
▸ Code
▸ All applications should compile with no issues. If there are issues with third-party
frameworks, they should be noted in the comments.
▸ Code Comments
▸ All applications should be verbosely commented so as to be understood by a third
party. The following rules should be applied throughout the code:
▸ Each custom class should include a short description of its functionality
▸ Non-standard methods should include a name, abstract, and description

FINAL PROJECT
▸ Logging
▸ Any data that is important to the normal flow of you application should be logged out to the
console. For example:
▸ All file paths and URLs
▸ Any target-action methods (e.g. a button pressed)
▸ Any data downloaded from the Internet
▸ Splash Screen
▸ Applications should show a splash screen with (at least) their name and the name of the
application. 

FINAL PROJECT
▸ Application Operation
▸ Applications should operate under all multi-tasking
▸ Launching
▸ Transition to background
▸ Being awaken
▸ Being terminated
▸ Instructions
▸ Applications should provides instructions for use (e.g. splash screen, info button, etc.) somewhere in
the application.

FINAL PROJECT
▸ Connectivity
▸ If application requires Internet connection, either 3G or Wi-Fi, the application should should operate
under all normal usage conditions.
▸ If necessary, it should degrade functionality if appropriate. For example:
▸ Present an alert notifying user that one cannot be found
▸ Cache data needed for uploads
▸ Handle airplane mode
▸ Correctly handle user’s choice to share location data
▸ Present activity monitor during Internet usage

FINAL PROJECT
▸ Performance
▸ All applications will be tested on a device, not on the simulator
▸ If possible, please test applications on devices
▸ Utilize techniques for handling large operations in background threads. For example:
▸ Requesting data from Internet
▸ Image manipulation
▸ Adaptive Layout
▸ Your application can use whatever layout is appropriate
▸ If appropriate, ensure that you use adaptive layout techniques to make sure the content looks good across all
devices

FINAL PROJECT
▸ Data
▸ It is not a requirement to have the application interface with outside data
sources.
▸ It is acceptable to fake the server calls and download a static file.
▸ Icons
▸ Applications should have all the appropriate icons for each capable device
and display (e.g. retina).

FINAL PROJECT
▸ Settings
▸ Every application should include a Settings.bundle to handle user preferences.
▸ The bundle should have, at minimum, a row with the developers name.
▸ More rows can be added as needed for the app.
▸ In addition the application should have the following behavior:
▸ Initialize the user preferences at launch
▸ Create a user preference named “Initial Launch” that store an NSDate on first launch

FINAL PROJECT
▸ Alerts
▸ Applications should utilize an alert within the application.
▸ If it is not part of the normal user interface of your application, Have the alert
view prompt users
▸ “Rate this App” in the app store on the 5th launch.

FINAL PROJECT
▸ Marketing Materials
▸ Each developer should prepare marketing materials for their application
▸ Submit along with the application code.
▸ These should include the same information that is required for an App Store submission:
▸ Define a category
▸ Description (2000 character max)
▸ Keywords (100 characters)
▸ Screenshots (up to 5 per device)
▸ Define age group

FINAL PROJECT
▸ Executive Summary
▸ Provide a one page summary of the application and its features.
▸ Discuss the problem that it solves for the user and how it fits into the App Store
landscape.
▸ If the app is for private company use, define its utility in the organization.
▸ Include a high-level overview of the technical details about the app.
▸ For example, this app collects location data based, aggregates it on a server and
broadcasts it to a group of predefined users.

GRADING
▸ All applications will be graded for implementing and complying the above
specifications.
▸ The completeness of the app is the most important objective, not necessarily a
full implementation of the developers vision
▸ Apps will be graded on implementation not idea
▸ Highest graded apps will be App Store ready

PRESENTATIONS
▸ Present your app the last day of class
▸ You must have a demo copy to me by that day

DUE DATE
▸ Projects are due:
▸ August 31, 2016 (Wednesday after finals week class)
▸ Code, marketing materials submitted

**Comment by tabinks** [comment]
I was going to post this with tomorrows lecture, but since everyone is so anxious....

[2016-Summer-FinalProjectRequirements.pdf](https://github.com/uchicago-mobi/2016-Summer-Forum/files/429339/2016-Summer-FinalProjectRequirements.pdf)
