### ISSUE TITLE
Back button

### ISSUE THREAD

**Issue by jvmakin** [uchicago-mobi/2016-Summer-Forum#110]
I embedded a table view in a navigation controller and created a segue from the table cells to another view. According to the ~internets~ this should automatically create a back button to return from the second view to the table view...alas this is not happening. Any ideas? Thanks!

**Comment by kbsrunschi** [comment]
I did the same (main view is embedded in a nav view and then i have a table view controller coming off of it with a segue) and the back button was auto added. Maybe delete and retry?

**Comment by susanstevens** [comment]
What kind of segue are you using? It should work with a show segue.

**Comment by jvmakin** [comment]
On the up side, the bar button is being auto added. 

On the down side, I can't seem to change the color. How can I do that?

**Comment by susanstevens** [comment]
Try changing the tintColor on the navigation bar. It should change the color of the back button text and arrow.

**Comment by tabinks** [comment]
If you want to change it app-wide, you can change the tintColor using appearance proxy.
