### ISSUE TITLE
Location services not being prompted

### ISSUE THREAD

**Issue by kbsrunschi** [uchicago-mobi/2016-Summer-Forum#111]
My location services url is still not being prompted to the user even after adding the plist key value pairs info (See latest commit). Any ideas?

**Comment by kbsrunschi** [comment]
Also my logger helper isnt writing the file specified - any ideas? Thanks!

**Comment by susanstevens** [comment]
What authorization status are you getting back from the location manager? Not determined?

I can take a look at your repo later today.

**Comment by tabinks** [comment]
Remember that it will only show a single time on a device.  Try switching to a new device in the simulator to see if that was the case.  I know that sometimes you can loose track of when you saw the dialogue on a specific device.

**Comment by susanstevens** [comment]
Check the keys in your Info.plist. They should be all one word (no spaces).

**Comment by susanstevens** [comment]
Also, for your logging helper, it looks like you're trying to write to a file in the main bundle. I don't think Xcode permits that. Is there a reason that you don't want to just print to the console?

**Comment by kbsrunschi** [comment]
all better!
