### ISSUE TITLE
throwing a nil but no nil found

### ISSUE THREAD

**Issue by kbsrunschi** [uchicago-mobi/2016-Summer-Forum#113]
In my transaction view detail controller, I put a breakpoint/printed out the variables and nothing is nil, but its still throwing an error when I try to save

Steps to recreate:
launch app
click Transactions
Click + to add a new transaction
enter date, amount, merchant, account, pick category
click save

**Comment by kbsrunschi** [comment]
Also how do I load a user? If you look at SpendCategories file, I am trying to load User (like we did in Food tracker) and then load the user info from there but its telling me I need to pass it parameters.

**Comment by susanstevens** [comment]
Can you explain your questions a bit more? If you're getting an "unexpectedly found nil" error, I would look for something optional that's being used or unwrapped on the line where's it's crashing.

**Comment by kbsrunschi** [comment]
Yea its not liking how Im changing the object types of some of my variables.. Ill keep looking. 

What about loading a user? I am trying to load the defaults but cant instantiate without parameters (although I can in transactions and meal from meal tracker...) what is different about my User object?

**Comment by kbsrunschi** [comment]
UPDATE in case others have my issue - NSNumberFormatter returns NIL if there is no currency symbol!

**Comment by kbsrunschi** [comment]
as for loading the user -> it looks like I just needed to do a clean build, I still have to instantiate it for now, but its saving the data correctly

**Comment by tabinks** [comment]
That sounds like a frustrating bug.  When in doubt, "Clean Build"!
