### ISSUE TITLE
New cell labels not showing up

### ISSUE THREAD

**Issue by kbsrunschi** [uchicago-mobi/2016-Summer-Forum#114]
After I add a new transaction, the new cell is created but the labels arent updated - if you go back to Main and then back to Transactions then it shows up, and if you click the empty cell it shows the data in the detail view -- but wont show the info on that first load after a save -- any ideas?

**Comment by tabinks** [comment]
Just because you change the data in your cell, it doesn't mean that the cell is updated.  You need to have the cell (or table) redraw itself to reflect the changes.  Try to reload the table after you add the cell.

**Comment by kbsrunschi** [comment]
Ive tried adding reload Data in a few places to generate the drawing but nothing so far. Ill keep trying.

**Comment by tabinks** [comment]
If you post it github, I can take a look at it.

**Comment by kbsrunschi** [comment]
Looks like it fixed itself with a delete and a rebuild :)
