### ISSUE TITLE
App Engine Launcher?

### ISSUE THREAD

**Issue by fungedwin** [uchicago-mobi/2016-Summer-Forum#115]
I downloaded the App Engine SDK for Python (https://cloud.google.com/appengine/downloads) but I don't see a GoogleAppEngine.dmg file after unzipping.  How do I open up App Engine Launcher (slide 193, lecture 9)?

**Comment by tabinks** [comment]
The bundle should've been downloaded when you clicked on the link. You have to run the standard Mac installer. After that he will ask you if you want to install some links to everything. You should do this. 

Look inside your applications directory to see if you can find it. This is after you've installed it.
