### ISSUE TITLE
First load of object from phone data is nil as expected but not getting handled correctly

### ISSUE THREAD

**Issue by kbsrunschi** [uchicago-mobi/2016-Summer-Forum#116]
When using this to load User from stored data on the phone: 
return (NSKeyedUnarchiver.unarchiveObjectWithFile(User.ArchiveURL.path!) as? User)!

it returns nil as expected because its the first time the user is being loaded. However, its breaking and not being caught by the else clause for Login Controller. Why would this be happening?

**Comment by susanstevens** [comment]
Hmm. The problem might be with the exclamation point at the end of that line. Looks like you're force unwrapping a nil value. You should return an optional instead.

**Comment by kbsrunschi** [comment]
ugh yes, i knew that. Thanks!
