### ISSUE TITLE
Multiple apps without paid Developer Account in Xcode 7

### ISSUE THREAD

**Issue by naietsg** [uchicago-mobi/2016-Summer-Forum#117]
Did anyone ever figure this out — I had been able to somewhat skirt around the “provisioning profile” warnings, but now am unable to do so as  "creating a profile requires having a device registered in the member center.”

**Comment by tabinks** [comment]
What exactly are you trying to do?  Are you just trying to get it on a device?  There is no limit, as far as I know, to put apps on your device for non-paid accounts.

**Comment by jbairUChicago** [comment]
Without a paid account, I was able to do one app on the device at a time. The previous weeks apps would no longer function. I don't know if it had to do with a single app limit or the cert expiring.

When it's time for XCode to deploy the test app to your device, your Apple Developer account is party to the certificate it uses. 

You can make sure that XCode has at least communicated with your device correctly if there is a Developer area under the Settings app. From the XCode side, management is under Window -> Devices.

**Comment by tabinks** [comment]
Thanks @jbairUChicago.  I may not be the best person to answer this because I've a paid account since the beginning.
