### ISSUE TITLE
Splash Screen Requirement

### ISSUE THREAD

**Issue by jbairUChicago** [uchicago-mobi/2016-Summer-Forum#122]
My question is in regard to this requirement:

> Applications should show a splashscreen with(atleast) the developer’s name and the name of the application. This should appear when your application launches. This is not the same as the Launch Screen that is provided in Storyboard.

Do these items need to be pulled dynamically? As I understand it, no custom code is executing at the point that the out of the box launch screen is being displayed so a storyboard/xib/custom view needs to be loaded in the AppDelegate (which supports the statement about this not being the same as the Launch Screen storyboard).

Second question is, does this need to display each time the app is opened or resumed?

**Comment by susanstevens** [comment]
Your name and the name of the app can be hardcoded. The splash screen should display each time the app comes into the foreground (whether it's a fresh launch or from the background).

**Comment by tabinks** [comment]
Agreed.
