### ISSUE TITLE
Playground

### ISSUE THREAD

**Issue by naietsg** [uchicago-mobi/2016-Summer-Forum#13]
I have finished the tutorial and finished foodtracker, but am confused as what we are supposed to do in the playground — are we just supposed to do the experiments? 

also, there is an option to download the foodtracker app as I believe we are supposed to submit it. Am i missing something here?

thanks

**Comment by susanstevens** [comment]
Yes, you should go through the playground and do the experiments. We'll be looking to see that you changed some of the code. Make sure you include the playground in your repository.

And yes, it's possible to download the food tracker app. Please don't do this. Working through the tutorial will help you learn some fundamental concepts that you'll need later on, so it's to your benefit to read everything carefully and do the work yourself.

**Comment by naietsg** [comment]
Cool. Thanks!
