### ISSUE TITLE
today's class

### ISSUE THREAD

**Issue by pikashoes** [uchicago-mobi/2016-Summer-Forum#14]
Hello,

I'm not going to be able to make class today -- just landed in Chicago on a flight due to a delay. Even if I take a cab straight to school, I probably won't make it in time. I do recall that this week, we are deciding on presentation dates -- will this be in class or online?

Additionally, other than looking through the slides and trying the tutorials, is there any other recommended way to make up today's missed class so I don't fall behind?

Thank you!

**Comment by susanstevens** [comment]
We haven't decided on presentation dates yet. Stay tuned for that!

Definitely go through the slides and use the tutorials posted on the class website. And if you have questions about any of the material, be sure to post on the forum or come to office hours.
