### ISSUE TITLE
Swift shortcuts

### ISSUE THREAD

**Issue by kbsrunschi** [uchicago-mobi/2016-Summer-Forum#15]
[PDF Shortcuts (short)](https://swifteducation.github.io/assets/pdfs/XcodeKeyboardShortcuts.pdf)

[Developer Shortcuts (long)](https://developer.apple.com/library/mac/documentation/IDEs/Conceptual/xcode_help-command_shortcuts/MenuCommands/MenuCommands014.html#//apple_ref/doc/uid/TP40010560-CH2-SW14)

**Comment by jbairUChicago** [comment]
I also can't recommend [**Dash** for OS X / macOS](https://kapeli.com/dash) enough. If you're working in any other editor besides XCode, it provides documentation for over 150 technologies/languages and integrates well with desktop utilities like Alfred and editors like SublimeText. 

It's also available on iOS. 

![Sample Screenshot](https://kapeli.com/img/dash-s1.png)
