### ISSUE TITLE
Confused over label fade-in/fade-out

### ISSUE THREAD

**Issue by tjp36** [uchicago-mobi/2016-Summer-Forum#19]
I am having trouble figuring out how to simultaneously fade out one label while fading in another.  Right now, I have the following function handling the fading in/fading out:

`func scrollViewDidScroll(scrollView: UIScrollView) {
        print(scrollView.contentOffset)
        self.label.alpha = 1.0 - ((scrollView.contentOffset.x % 375) / 375.0)
    }`

along with my implementation of the scrollViewDidEndDecelerating to determine which label should apply.

However, the problem with this is that it only fades out the label as I scroll and does not fade in the new label.  In addition, the new label appears abruptly and is not smooth.  I don't see how I could fade in the new label with the above approach as the label can only have one set of text at any given time.

Is there some special animation property/function that we should be aware of in UIScrollView or UILabel that would make this easier?  Am I completely missing something? 

Thanks

**Comment by tabinks** [comment]
There are some more `UIView` animation methods that we will talk about in future classes (https://developer.apple.com/library/ios/documentation/WindowsViews/Conceptual/ViewPG_iPhoneOS/AnimatingViews/AnimatingViews.html).  You shouldn't need them for this assignment.  Instead, you should do the inverse adjustment of the alpha property for the next label.  

For example:
- Label1 is visible (alpha=1)
- Label2 is the next label and not visible (alpha=0)
- As you scroll Label1 adjusts from 1 to 0 and Label2 adjusts from 0 to 1

**Comment by tjp36** [comment]
So, we should have 3  UIIlabels instead of 1?  This would make this easier.  The instructions only specify one:

> Add a UILabel to your scene at the bottom of the screen. Make the label the width of the screen. The height should be 167px. This label is outside of the UIScrollView (i.e. it will not scroll with the rest of the screen).

**Comment by tabinks** [comment]
@tjp36 There are many different approaches to accomplishing this.  This is just one.  No way is necessarily "better".
