### ISSUE TITLE
Creating an extension on Array

### ISSUE THREAD

**Issue by pikashoes** [uchicago-mobi/2016-Summer-Forum#25]
I'm a little stumped on this part:

> Create an Extension on Array that provides a new method shuffle() that randomly shuffles the contents of an array. After loading the data in the Animals array, call the shuffle() method. This should cause the animals to be in a different order every time the app is launched.

I'm not sure if this was something that was covered in class? If so, could someone point me to the section where this was covered (or any online resources that explains what this means)?

I've checked StackOverflow and Google, and the best I could come up with is:

```
extension Array where Element:ViewController
{
    func shuffle() -> [Animal]
    {

    }
}
```

Which I put after closing the bracket for the class ViewController.

Also, I haven't gotten to the next section yet, so I'm not sure if this is resolved later, but when I create three animals, I need to initialize them with values and an image. Do I just put the image into the same directory and call the name of the file (ignoring the path)? In my past experience with Java, we had to ensure that the path was included and throw errors, so I wanted to make sure.

**Comment by kbsrunschi** [comment]
thats what I came up with too... And I too am confused how to load images... the best I can determine is that you save the picture (not sure where to save it to) with the same file name as what you load in image: UIImage(named: "elephant")!

**Comment by pikashoes** [comment]
The progress I've made so far:

```
extension Array
{
    func shuffle() -> [Generator.Element]
    {
        // Insert code here
    }
}
```

I found that using this allows me to call the method shuffle on an Array in my controller. The code I have to write is just the actual shuffling, so I think as long as that works, that part of the question is ok.

But yes, I still am wondering about images! I'm going to try to save some files into my directory and see what happens.

**Comment by tabinks** [comment]
## Extensions

I talked about class extensions in the context of protocols, but they work the same way.  They extend the functionality of a class.  The useful thing is that it can be a class that you did not write.  This is how we can extend the capabilities of `Array` that is implemented by Apple.  When you extend a class it is available to all instances of that class, regardless of where the actual code is located.

The code you showed above is the correct way to implement an extension.

**Comment by tabinks** [comment]
## Images

We discussed two ways of loading images in class, using the Asset Catalog and loading directly from the bundle.  We also discussed the different inherent behaviors that each of these methods have in regards to caching. Here is the basic flow for loading an image from Asset Catalog.  

``` swift
// Remember that an image is displayed in a UIImageView
let imageView = UIImageView(frame: CGRectMake(100, 150, 150, 150));
// Load image from asset catalog
var image = UIImage(named: "ImageNameInAC");
// Set the image property of an image view
imageView.image = image;
view.addSubview(imageView);
```

Remember that you have to add the images and set a name for the images in asset catalog.  The name of the actual image does not matter in asset catalog, only the name you set.

See the slides for an example of how to load the image from the main bundle.

**Comment by pikashoes** [comment]
Ok, thank you!
