### ISSUE TITLE
Scroll not scrolling

### ISSUE THREAD

**Issue by kbsrunschi** [uchicago-mobi/2016-Summer-Forum#26]
I have created a @IBOutlet var scrollView: UIScrollView! with it linked in the storyboard, set the scrollview width and height to 375 x 500 and set the content size as 1125x500 with paging enabled but my app does not scroll. 

Added it as a subview, added its delegate as itself, used the extension code for scrollViewDidScrool and scrollviewdidenddecelerating but nothing. Any ideas?

**Comment by susanstevens** [comment]
Are you sure it's not scrolling?  If the content size is larger than the frame, it should scroll.  The only reason it wouldn't is if you accidentally disabled user interaction.  You could double-check that the box for "User interaction enabled" is checked in storyboard.

Also, keep in mind that anything you drag onto the view controller in storyboard doesn't need to be added as a subview programmatically.  However, you should be programmatically creating images and buttons, and adding them as subviews of the scroll view (i.e., don't try to do that part in storyboard, at least for this assignment).

**Comment by kbsrunschi** [comment]
Yup its definitely not scrolling, I checked all the parameters and did some googling, but no dice. I pushed my latest code to my repo, its failing right now because of audio nulls but can you see if you can find something? I must have wired something incorrectly.

**Comment by kbsrunschi** [comment]
And because it doesnt scroll/none of the images are being added, Im coding blind and unable to see if any of my code works :(

**Comment by kbsrunschi** [comment]
Also its refusing to let me add an App/launch icon. I might need to start over from scratch.

**Comment by susanstevens** [comment]
I downloaded your project, and I can see the scroll view scrolling.  The horizontal scroll indicator is moving left and right.

This is unrelated to the scrolling, but it looks like you're adding image views and buttons both programmatically AND in storyboard.  You don't need to do both -- just create and add the image views and buttons in code.  All your storyboard needs is the scroll view and a label.

(Also, if you're having trouble loading images into your image views, try `UIImage(named: "Cat")`.  If you have an image called Cat.jpg or Cat.png in Assets.xcassets, Xcode will find it.  No need to specify the bundle or anything.)

**Comment by kbsrunschi** [comment]
Ok i started over and I cant see the scrolling so Ill keep trying. 

And thank you - i wasnt sure as the hw instructions list a ui image and button in the pictures but we're told to do it programmatically so it was confusing. Im having trouble wiring everything up with the images/buttons

**Comment by kbsrunschi** [comment]
also my audio player is coming back nil which doesnt make sense as I made it optional (?) and Im passing it the file name and type... i stored the sounds in the Assets... is it the same thing that if I move the sound files into the asset folder then I dont need the NSBundle etc?

**Comment by kbsrunschi** [comment]
also the instructions say to create an array in viewDidLoad and add a property in the main controller to hold that array... are those two separate arrays or one array (as Im doing it in my code)

**Comment by kbsrunschi** [comment]
I have an image and button loaded but still no scroll (in Its a Zoo 2)... im slowly going insane haha :)

**Comment by susanstevens** [comment]
Hmmm... I'm looking at your new project in the simulator, and I'm definitely seeing scrolling.  So what you have is working, you're just not able to see it for some reason!  Are you running it in the iPhone 6 simulator?  In portrait mode?

**Comment by kbsrunschi** [comment]
Yup, I cant see the scrolling at all despite setting everything up correctly

**Comment by kbsrunschi** [comment]
im going to at least try to get what i can see working... how do i wire the button? I have it on the page but nothign happens when i click it

**Comment by kbsrunschi** [comment]
nvm I think for the button i have to add a target...

**Comment by kbsrunschi** [comment]
@susanstevens i just pushed the latest with working images/button but no scroll (to me) but with all the images/buttons -- Its a Zoo 2 - can you tell me if the scroll has multiple images or just the one?
