### ISSUE TITLE
Audio files

### ISSUE THREAD

**Issue by kbsrunschi** [uchicago-mobi/2016-Summer-Forum#27]
So outside of my scroll issues, the last issue Im having is that the audioplayer url is being returned as null. I loaded the sounds into my assets collection and passed the name and file type to the NSBundle per [this website](https://www.raywenderlich.com/114298/learn-to-code-ios-apps-with-swift-tutorial-5-making-it-beautiful) but im getting EXC_BAD_INSTRUCTION which I know is because it cant find the file.

Where are we supposed to store audio files? In the assets collection is not working.

**Comment by naietsg** [comment]
Having the same problem

**Comment by kbsrunschi** [comment]
Googling at length and all I can determine is that the audio files do not belong in the asset folder like images... but even when I put them in my project folder, it cant find them. And Im using the code exactly as laid out above.

**Comment by adlee-dev** [comment]
I basically used the code found here:

http://stackoverflow.com/a/31716861

but set ofType to nil because of how I set the sound variable in the Animal
class

I also stored the sound files in the same folder as ViewController and the
other code files

**Comment by kbsrunschi** [comment]
OK So I had been putting it into the folder but not dragging it into XCODE -- that was the key. Drag and drop from the folder into xcode idea and say OK when asking to make folders/copy. Then it will show up in IDE rather than just in folder.
