### ISSUE TITLE
Assignment 3

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2016-Summer-Forum#28]
Assignment 3 has been posted in the Session Notes: http://uchicago.mobi/sessions/session3/.  You will be completing the Food Tracker application from Apple's tutorial.  I would recommend starting completely over from a new project to help reinforce some of the topics we have been discussing.

Also, it will be very helpful to look through the document on some of the new classes and controls that are introduced (eg. UITableView, NSCoding, etc.).  The tutorial does a nice job of showing how to use them in one particular way, but reading the documentation will show you the additional capabilities of these classes.

Repo Link: https://classroom.github.com/assignment-invitations/f01a81ebb9ad94add1baaa223ac38abb

**Comment by tjp36** [comment]
Just to be clear, we should go all the way through the table views section (i.e. complete everything on the page of the assignment link)?

**Comment by susanstevens** [comment]
You should complete the entire tutorial.  You should also comment all of the functions and variables in the tutorial, using header documentation.  See the links on the assignment page for how to format header doc comments.

**Comment by hiesenburg88** [comment]
@susanstevens following up on this last comment you made, the comments that were provided in the tutorial (with the appropriate headers) are sufficient for this assignment correct? Or are you looking for us to provide additional original comments in the code, describing the purpose of functions, variable usage, etc?

**Comment by susanstevens** [comment]
The latter.  The assignment asks you to document all functions and variables (i.e., class variables -- you can leave local variables inside functions uncommented).  Make sure you're using header doc style comments, not just regular comments.
