### ISSUE TITLE
Office Hours Friday 5:30-7:30pm at Gleacher Center

### ISSUE THREAD

**Issue by susanstevens** [uchicago-mobi/2016-Summer-Forum#30]
I'll be out of town this weekend, so my office hours this week will be on Friday from 5:30 to 7:30 pm at the Gleacher Center cafeteria.  If you're planning to stop by, please post a reply here to let me know!  (I might cancel if no one's planning to attend.)

Also, I'll still be available to answer questions on the forum over the weekend.  There have been some great questions so far -- keep up the good work! 😀

**Comment by tabinks** [comment]
Yes, please don't be hesitant to post to the forum.

**Comment by tabinks** [comment]
test

**Comment by tabinks** [comment]
test

**Comment by tabinks** [comment]
test again...

**Comment by tabinks** [comment]
test

**Comment by susanstevens** [comment]
Any takers for office hours tonight?  Please post here if you're planning to attend.  If I don't hear from anyone by 3pm today, I'll cancel office hours for tonight.

**Comment by susanstevens** [comment]
Okay, no office hours tonight!  Don't forget to post to the forum if you have any questions over the weekend! 👍
