### ISSUE TITLE
Source-based Documentation

### ISSUE THREAD

**Issue by jbairUChicago** [uchicago-mobi/2016-Summer-Forum#32]
Semi-related to issue #28, I have some questions about the generation of documentation comments in XCode + Swift. 
- Are there any default shortcuts or actions to output a documentation snippet (like typing `///` in many IDEs to generate a documentation block above a function?
- What level of 3rd party contributions does XCode support. Would it ever be possible for something like Doxygen or GhostDoc to be integrated? 

Regarding the last question, it seems like there isn't much native guidance or built-in functionality for HOW documentation should be done.

I did try out [Jazzy](https://github.com/realm/jazzy), a Ruby gem that you execute at the root directory of your XCode project. Its output is a doc directory containing a Javadoc-like site that you can upload. _Note: You must have Ruby 2.2 or higher_. This worked well (with some tuning of the arguments to make it more verbose), honored the Markdown in the comments, and was easy to host since it is static content.

Example screenshot of Jazzy:
![Jazzy Swift doc screenshot](https://raw.githubusercontent.com/realm/jazzy/master/screenshot.jpg)

**Comment by tabinks** [comment]
I'll show you in class tonight.
