### ISSUE TITLE
Case Study Signup Do-over and Vice Lipstick

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2016-Summer-Forum#39]
It looks like my form was missing a very important piece of data...your names.  Can you please fill them out again?  Sorry.

Please fill out: http://goo.gl/forms/1Xxtf3V28eDVbZiP2

Thank you to whoever was planning to present "Vice Lipstick".  They will be presenting at the next class.

**Comment by jvmakin** [comment]
That would be me >_<

**Comment by tabinks** [comment]
@jvmakin Great.  Can't wait to hear about it...
