### ISSUE TITLE
Office Hours Wednesday 10:00AM to 12:00PM in Young 308

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2016-Summer-Forum#4]
See you tomorrow.

**Comment by kbsrunschi** [comment]
Will these always be be hours? I work full time and would never be able to
make them. Can i schedule a different time as needed in the semester?

Thank you :)

**Comment by tabinks** [comment]
@kbsrunschi Yes, this will be my normal office hours.  @susanstevens will have office hours that should be more amenable to working students.  I will stay after class to help out and can make other arrangements as needed.

**Comment by kbsrunschi** [comment]
Thanks! :)
