### ISSUE TITLE
Office Hours Sunday 10am to noon

### ISSUE THREAD

**Issue by susanstevens** [uchicago-mobi/2016-Summer-Forum#40]
My office hours this weekend will be on Sunday from 10am to noon in Young 302.  See you there!

**Comment by kbsrunschi** [comment]
Thank you!

On Wednesday, July 13, 2016, Susan Stevens notifications@github.com wrote:

> My office hours this weekend will be on Sunday from 10am to noon in Young
> 302. See you there!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/uchicago-mobi/2016-Summer-Forum/issues/40, or mute
> the thread
> https://github.com/notifications/unsubscribe/AOOS4ubKef_PMQtgBXwzk5lT7eLyZx-Jks5qVaWpgaJpZM4JMCcD
> .

## 

---

Kathryn Smith

Click here http://chicago.chicktech.org/ to support ChickTECH & help keep
girls in STEM!
