### ISSUE TITLE
Github API Missing first 6 issues

### ISSUE THREAD

**Issue by naietsg** [uchicago-mobi/2016-Summer-Forum#41]
The first issue that appears is "Swift requirement of specifying names for subsequent method arguments?". Is there something I don't understand about the API ([link](https://api.github.com/repos/uchicago-mobi/2016-Summer-Forum/issues?state=all)) or are other people having this issue?

**Comment by benvcarr** [comment]
The GitHub API is limited to 30 issues by default in a response - you'll either have to paginate through the rest of the issues or request a higher default (max 100).

See: https://developer.github.com/v3/#pagination

**Comment by naietsg** [comment]
that would do it. Thanks!
