### ISSUE TITLE
MainViewController

### ISSUE THREAD

**Issue by kbsrunschi** [uchicago-mobi/2016-Summer-Forum#42]
Is this supposed to be kept and attached to one of the views (possible the main tab controller)? Every where Im trying to put code, I am getting errors saying that the code is not allowed on the tab view controller type. My storyboard looks just like the picture but Im having issues.

**Comment by kbsrunschi** [comment]
Ill be at office hours tmrw bright and early as well, we can discuss then if my code is too much of a mess :)

**Comment by susanstevens** [comment]
I'm not sure what you mean by MainViewController.  If you're trying to subclass `UITabBarController`, you don't need to do that for this assignment.  

You should have a `UITabBarController` in storyboard, and then several navigation controllers and regular `UIViewControllers`.  The only view controllers for which you need .swift files should be your `IssueViewController`, `AllIssuesViewController` and `CircleViewController`, which should all be subclasses of `UIViewController`.  (Same goes for the `IssueDataController` if you choose to implement it.)

We can definitely talk more at office hours tomorrow. :)

**Comment by kbsrunschi** [comment]
When I do the api call, the issues arent being stored in the array (I can print them in the function but printing outside the function after the call is done results in an empty array). What am I doing wrong?

**Comment by susanstevens** [comment]
You have a local variable called issues that's being populated by the API call, and you have a property self.issues on your view controller that is nil until you give it a value. My guess is that you're not assigning your local variable to your class property.

**Comment by kbsrunschi** [comment]
Right, so the question is how do we set it? Passing in self.issues doesnt work, setting self.issues = issues doesnt work, it doesnt return anything so self.issue = getIssues(...) doesnt work. I added "completion(issues), but I cant really tell where I set my class variable to whats happening in the closure. I read the documentation and am reading the playgrounds/searching online for more info but coming up at a dead end after a few hours of reading.

**Comment by kbsrunschi** [comment]
OK nvm I think I finally got it... 100th combination was the charm :)

**Comment by susanstevens** [comment]
Okay, good!  Yeah, if you're able to print out the issues in the `getIssues` closure, then you know you've downloaded them properly.  Right after your print statement is a good place to set `self.issues`.

**Comment by kbsrunschi** [comment]
So now I know Im getting data, but nothing is showing up in my table view. Im double checking things against Food Tracker but not seeing why tableView() isnt loading up the cells.

**Comment by kbsrunschi** [comment]
Actually no i see, the in the tableviews i still had number of sections/rows = 0 and my issues array isnt populating

**Comment by susanstevens** [comment]
So your `issues` array is still nil?  Make sure you're setting it in the `getIssues` closure.  Maybe print out `self.issues?.count` in the closure and see if it's being set properly there.  It sounds like your tableview delegate methods are being called, so that's not the issue.

**Comment by kbsrunschi** [comment]
Yes so i figured out its because i needed to have tablevuew number of rows in section = the count of openissues array, but that was getting populated and now its not. Ill keep playing around with it

**Comment by kbsrunschi** [comment]
Yes so no matter what, it goes straight to "return self.openIssues?.count" which is nil, and the getIssues function is no longer executing

**Comment by kbsrunschi** [comment]
OK so my issue is that the code is jumping right to the number of rows section before the openIssues array can be initialized. So im trying out different ways to initialize it safely

**Comment by tabinks** [comment]
That's a perfect place for an if-let.  If there are no issues ( because the networking call hasn't returned yet ), then return 0.

**Comment by kbsrunschi** [comment]
:) just what i was gonna try

**Comment by kbsrunschi** [comment]
So after getting that working - its still not updating after the api call is done - I think im refreshing the data correctly - do you see what Im missing to get the data to load into the cells?

**Comment by susanstevens** [comment]
I just looked at the code you have in your repo, and it doesn't look like you're setting `self.issues` in the closure for `getIssues`.  You're setting the target action for your `refreshControl`, but this is just specifying which method should be run when the refresh control is activated.  It _isn't_ actually calling the method.  You should be setting the target action in `viewDidLoad()`, but not in the closure for `getIssues`.

In the closure for `getIssues` you should set the data for `self.issues`.  Then you should move from the background thread (which you're on by default here) to the main thread.  Once you've done that, you should reload your table view.

Also -- make sure that your `refreshTable` method is actually making a service call to get fresh data.  It's not doing that currently.

**Comment by kbsrunschi** [comment]
I dont have a variable self.issues, on line 208 i have self.openIssues = issues? Is there something else I need to set?

**Comment by susanstevens** [comment]
Oh, I see.  That should work.  You still need to call `reloadData`, though.  I see that you have it in `refreshTable`, but I don't see where `refreshTable` is being called (unless the user activates the refresh control with a pull-to-refresh action).
