### ISSUE TITLE
Number of results returned by API capped at 30

### ISSUE THREAD

**Issue by adlee-dev** [uchicago-mobi/2016-Summer-Forum#43]
According to the GitHub API documentation the results are generally capped at 30 per page. Since the links provided in the instructions don't increase the size of the result set, am I correct to assume that we don't need to worry about the other pages? (For what it's worth, there are only two pages from what I can tell).

**Comment by naietsg** [comment]
you can up the pagination (though this is sort of a cop out too). 
e.g. https://api.github.com/repos/uchicago-mobi/2016-Summer-Forum/issues?state=closed&per_page=100

**Comment by tabinks** [comment]
You can limit the results to the default 30 results.
