### ISSUE TITLE
Running apps on a device with Xcode

### ISSUE THREAD

**Issue by susanstevens** [uchicago-mobi/2016-Summer-Forum#44]
During office hours today, a couple students asked me about running their apps on a device.  Here are some steps to get you started, in case anyone else is wondering about this too.
1.  You'll need to set up a free Apple developer account.  If you're doing a free account, click on this [link](https://idmsa.apple.com/IDMSWebAuth/login?appIdKey=891bd3417a7776362562d2197f89480a8547b108fd934911bcbea0110d07f757&baseURL=https://developer.apple.com/&path=%2Faccount%2F&rv=1).  If you already have an Apple ID (which you do, if you have an iPhone or iPad), enter your ID and password and hit "Sign In."  If you don't (which probably means you're borrowing a friend's device or something), you can hit "Create Apple ID."  At this point, the steps to set up your developer account should be straightforward (but let me know if they're not... it's been awhile since I've done this part).
2. Once you've set up your developer account, open your project in Xcode.  Click on the project at the top of the Project Navigator (the left panel).  Select your target, and then open the "Team" dropdown menu in the Identity section at the top.  Choose "Add Account" and enter your Apple ID and password when prompted.  Here's a screenshot:

![screen shot 2016-07-17 at 5 28 00 pm](https://cloud.githubusercontent.com/assets/10423328/16903493/984adb54-4c45-11e6-8d70-5e7a12e9c7ea.png)

You should now be able to select your name under Teams.  Next, plug your device into your computer.  Select your device from the drop-down menu where you would normally select one of the simulator options.  (Your device should appear at the top of the menu, but give it a few moments if you don't see it right away).  Now hit run, and the app should build and run on your device.

Let me know if you have any questions or run into trouble with any of this!

**Comment by naietsg** [comment]
This isn't working for me. I get the following error:

```
dyld dyld_fatal_error:
->  0x1fefd08c <+0>: trap   
    0x1fefd090 <+4>: nop    

Thread 1: EXC_BREAKPOINT(code=EXC_ARM_BREAKPOINT, subcode = 0xe7ffdefe)
```

I have tried clean/build and playing around with breakpoints to no avail. I am using an IPhone 5 with 9.3.2.
