### ISSUE TITLE
Having trouble getting data out of the getIssues() completion context

### ISSUE THREAD

**Issue by jbairUChicago** [uchicago-mobi/2016-Summer-Forum#45]
I'm using this getIssues function from the Fetching Issues playground:
`func getIssues(url: String, completion:([[String: AnyObject]]?) -> Void)`
and have a call implemented to it in a ViewController.  This controller has a property to hold these in:
`var openIssues: [[String: AnyObject]]?`

The call is working as I'm seeing the JSON output in the console. However, I'm having trouble with what to do within the context of the completion. I've tried assigning `(issues)` to `self.openIssues` but that doesn't seem to work (the variable stays nil).

I've also tried looping over objects in `(issues)` but breakpoints in that code don't seem to be hit. In the end, I just don't think I fully understand completions and how to get a copy of `(issues)` out of this function call.

I currently have:

```
var openIssues: [[String: AnyObject]]?
getIssues("https://api.github.com/repos/uchicago-mobi/2016-Summer-Forum/issues?state=open") { (issues) in
    self.openIssues = issues
}
```

**Comment by kbsrunschi** [comment]
I had the same issue - did you add 'completion(issues)' after putting the api response into issues (ie after you can print it out)? 

I also put self.issues = issues in the getIssues method

**Comment by jbairUChicago** [comment]
I've got a breakpoint at the bottom of my `viewDidLoad()` function (same one with the call to `getIssues()` and my openIssues property is still nil at this point (a symptom of the problem). Even stranger, the debug window has not output any of the print statements from the `getIssues` function yet, even though it has been called. When I hit continue, it then outputs all of the print statements from that function.

Is this due to the singleton session (NSURL.sharedSession) or perhaps my placement of the call in a `viewDidLoad()` function? In last week's Apple example, they loaded data from functions within the model.

**Comment by susanstevens** [comment]
My guess is that you're forgetting to reload data for your table view on the main thread in the `getIssues` closure.  The `getIssues` function makes a network call on a background thread, which means it might not be executed right away.  All of the code in the `getIssues` closure is also executed on a background thread, unless you specifically tell it to execute on the main thread.  

There's a section in the slides from the last class called "Getting Back on the Main Thread" that should be helpful.  You'll need to a) get back on the main thread, and then b) reload your table view.  (There is a method on `UITableview` that does this.)

Also, `viewDidLoad()` is a good place to call `getIssues`.  You're on the right track there.

**Comment by jbairUChicago** [comment]
I'm getting data back now. Thank you!

**Comment by jbairUChicago** [comment]
Though I've implemented code to get back to the main thread and thought I found what the function you were referring to in point B above (tableView.reloadData()), I still have a threading problem. It shows itself through the following behavior
- Empty issues table initially
- Continuous hits of a breakpoint on this function: 

```
override func tableView(tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return (self.openIssues.count)
    }
```
- In the above function, the count is 0 multiple times. 
- Then I see the data come back in the console, use a refresh control, and everything shows as expected. 

I think I might be over-implementing the main thread code or just incorrectly.

**Comment by susanstevens** [comment]
I took a look at the code currently in your repository, and it looks like there's a multithreading issue.  I'd recommend walking through `viewDidLoad` and thinking about what will execute on each thread, and in what order.  The `getIssues` function is making a networking call on a background thread, and nothing in its closure will execute until the networking call completes.  In the meantime, the rest of the code in `viewDidLoad` will execute on the main thread.

A good question to ask is whether `tableView.reloadData()` being called before or after the networking call completes and data is populated into the `openIssues` array.

**Comment by jbairUChicago** [comment]
Thanks @susanstevens. I got it just by taking out that extraneous reloadData call.

**Comment by susanstevens** [comment]
Nice work!
