### ISSUE TITLE
Unable to dequeue a cell with identifier

### ISSUE THREAD

**Issue by hiesenburg88** [uchicago-mobi/2016-Summer-Forum#46]
When I try switching from my Open tab to my All tab, my app is crashing with the following error message: **Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'unable to dequeue a cell with identifier AllIssuesTableViewCell - must register a nib or a class for the identifier or connect a prototype cell in a storyboard'**

I've read about this on [stackoverflow](http://stackoverflow.com/questions/12737860/assertion-failure-in-dequeuereusablecellwithidentifierforindexpath), and I've tried adding the following code to viewdidload(), without any luck. 
self.tableView.registerClass(AllIssuesTableViewCell.self, forCellReuseIdentifier: "cell")

Any suggestions?

**Comment by hiesenburg88** [comment]
figured it out. the identifier field was blank.

**Comment by tabinks** [comment]
You're fast... 👍
