### ISSUE TITLE
Case Study Schedule

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2016-Summer-Forum#48]
-  Kathryn Smith | Week 6 - July 25 |
- Josh Bair | Week 6 - July 25  |
- Mark McDonald | Week 7 - August 1 |
- Ben Carr | Week 7 - August 1 |
- Aaron Goldman | Week 8 - August 8 |
- Andrew Lee | Week 8 - August 8 |
- Edwin Fung | Week 9 - August 15 |
- Theodore Prekop | Week 9 - August 15 |
- Guofed Zhao | Week 10 - August 15  |

**Comment by tabinks** [comment]
This was my best scheduling based on preferences.  If anyone has a serious conflict, let me know and we'll work it out.  Also, if week 10 is open if any one would like to present then.

**Comment by benvcarr** [comment]
I might have made a mistake submitting the form - August 8 is the only week I _can't_ do, as I'll be out of town.

Anyone interested in swapping?

**Comment by naietsg** [comment]
^ yes, I am.

**Comment by benvcarr** [comment]
@aietsg - cool, thanks! I'm guessing by letters in your username you're Aaron Goldman?

**Comment by naietsg** [comment]
That is correct

**Comment by tabinks** [comment]
I'm switching it above...

**Comment by benvcarr** [comment]
Awesome, thanks to both of you!
