### ISSUE TITLE
Lecture 5 Playgrounds

### ISSUE THREAD

**Issue by tjp36** [uchicago-mobi/2016-Summer-Forum#49]
Would it be possible to get the Lecture 5 playgrounds put up on the forum?  I'd like to start playing around with them to aid me in creating this week's homework asssignment.

Thanks,

Ted

**Comment by kbsrunschi** [comment]
Also the repo for assignment 5 :) 👍

**Comment by tabinks** [comment]
Sorry.  I just posted it.
Github repo: https://classroom.github.com/assignment-invitations/d93f5c6517ddfa211387400940bcb192
