### ISSUE TITLE
Files are locked in Simulator

### ISSUE THREAD

**Issue by kbsrunschi** [uchicago-mobi/2016-Summer-Forum#5]
I can add the attributes and code to connect them, but when I run the simulator, the file is locked and I am unable to test whether my features are working or not. Moving the folder structure to different folders outside of git does not help.

![image](https://cloud.githubusercontent.com/assets/14914274/16251592/018ad410-37ed-11e6-8470-f7596a59e81b.png)

![image](https://cloud.githubusercontent.com/assets/14914274/16251597/0fbb4c54-37ed-11e6-869e-fddbcbeb87ba.png)

![image](https://cloud.githubusercontent.com/assets/14914274/16251599/17f0294e-37ed-11e6-83ca-bd89fe304487.png)

**Comment by tabinks** [comment]
This is odd.  Did you start by creating a new project first?

**Comment by kbsrunschi** [comment]
Yes

**Comment by tabinks** [comment]
So you created a project, then added all those files to the repo?

**Comment by kbsrunschi** [comment]
yes, created a new project, then I did a save-as into the location of the repo

**Comment by tabinks** [comment]
If committing all the files doesn't work.  I would just remove the .git/ folder and try again.  Something weird is going on with the git repo, it has nothing to do with Xcode or Storyboards.

You can do a `git init` to put it back under git control once you zap the old .git directory.

**Comment by kbsrunschi** [comment]
ok i will try that

**Comment by kbsrunschi** [comment]
I created a brand new blank project in a different folder and its still locked. Ill keep investigating. I pushed my code if you can try to run it to see if you are not locked.

**Comment by tabinks** [comment]
@kbsrunschi I'm looking at it now.

**Comment by tabinks** [comment]
When I ran it, I received this error:

```
2016-06-21 20:52:47.418 FoodTracker[91161:7346652] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<FoodTracker.ViewController 0x7af7cb50> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key setDefaultLabelText.'
*** First throw call stack:
```

It looks like you created an outlet connection to `setDefaultLabelText`, highlighted in red.  You also create an action to `setDefaultLabelText`.  You should delete the outlet by clicking no the "x".  Notice there is an "!" to show that there is a bad connection.

<img width="942" alt="screenshot 2016-06-21 21 03 30" src="https://cloud.githubusercontent.com/assets/93689/16252439/c0323510-37f3-11e6-8d98-31b2ab99ec58.png">

**Comment by kbsrunschi** [comment]
huh, thanks - ill check that out!

**Comment by tabinks** [comment]
This is a common error when starting out.  It's usually just because you clicked the wrong option when making the connection and didn't realize it.

**Comment by tabinks** [comment]
Other than that, I was able to run it without the locked message.

**Comment by kbsrunschi** [comment]
Ok. My code is still locked. Even when I start a brand new project, its locked.

**Comment by kbsrunschi** [comment]
so it looks like I can go to the Xcode > Open Developer Tools > Simulator and there I can launch the app. I will see if that gets me anything.

**Comment by kbsrunschi** [comment]
OK so yea once I hit Run and let it open by itself in the simulator, the keyboard works and I can test it. Not sure why I cant do the preview.

**Comment by susanstevens** [comment]
Glad you got it working. I'm not totally clear on the method you were trying that wasn't working, but let us know if you run into any more issues. Usually you'll just want to hit "Run" (the button in the top left that looks like a play button) and then give the simulator a few moments to pop up.

**Comment by kbsrunschi** [comment]
So when I do Command+R, no issues (run/build + simulator load). When I go to the right hand side and navigate to the venn diagram circles and use the drop down menu to go to Simulator (Preview) as specified in the instructions, the files are locked and nothing moves. I assume because its a preview and not the actual run maybe.
