### ISSUE TITLE
Assignment 5 Repo

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2016-Summer-Forum#50]
Repo: https://classroom.github.com/assignment-invitations/d93f5c6517ddfa211387400940bcb192

**Comment by tjp36** [comment]
Were the playgrounds we used in class put somewhere else?  I can't seem to find them on this forum.

**Comment by adlee-dev** [comment]
https://github.com/uchicago-mobi/MPCS51030-2016-Summer-Playgrounds

**Comment by tjp36** [comment]
Thanks!
