### ISSUE TITLE
Launch Screen Woes

### ISSUE THREAD

**Issue by jvmakin** [uchicago-mobi/2016-Summer-Forum#54]
So, if you're trying to make the launch screen...

I set up an image in the LaunchScreen.storyboard file and it appears to be set as the launch screen both in storyboard and in the main file...what am I missing?

It doesn't show up at all. :(

**Comment by susanstevens** [comment]
It's possible that your app is loading so quickly that you can't see the launch screen, even though it's flashing for a split-second.  In the simulator, try going to Debug and selecting "Slow Animations".  (The shortcut is Command+T).

Other things to double-check: You should have "Use as Launch Screen" checked in the File Inspector for your Launch Screen view controller.  It's under "Use Auto Layout" and "Use Size Classes".  And in Info.plist, there's a property called "Launch screen interface file base name" that should be set to "LaunchScreen".

**Comment by tabinks** [comment]
The other thing to check is that it will only show on a new launch, not being awakened from a suspended state.

**Comment by jvmakin** [comment]
Hmmm...I have tried everything you suggested and I still can't see it. When I use Command+T, I see a white screen but I have added stuff to my LaunchScreen storyboard. >_<

Is there a reason why the elements I have added wouldn't show up? Do I need to make a swift file?

**Comment by tabinks** [comment]
Is your code committed? I can take a quick look at it later.

**Comment by jvmakin** [comment]
Yes, please. 

The weirdest thing is that it displays for iphone 4s, 5, 6 plus...just not iphone 6. I've tried cleaning the files but it still won't show. >_<

**Comment by tabinks** [comment]
@jvmakin I didn't do anything to your project and I see the launch screen.  I see the pink screen that says "Hi there".

**Comment by jvmakin** [comment]
Huh. I guess its just my XCode then?

**Comment by susanstevens** [comment]
You might want to try resetting your simulator.  In the simulator, go to "Simulator", then "Reset Content and Settings..."  The other thing you can try is deleting derived data.  In Xcode, go to "Window", then "Projects".  Click the delete button next to Derived Data.

**Comment by jvmakin** [comment]
That fixed it! Thank you. :)
