### ISSUE TITLE
Super dumb question about tap gesture

### ISSUE THREAD

**Issue by kbsrunschi** [uchicago-mobi/2016-Summer-Forum#55]
I know Im over thinking this but for tap gestures... I put two pan gesture recognizers on my two game pieces, which will allow a user to drag the piece to a spot on the board and we can code to find where they land... we dont have to put tap recognizers on the game board... correct?

Or if we do, do we make it one big tap recognizer over the entire game board or 9 individual recognizers? 

Thanks!

**Comment by susanstevens** [comment]
You shouldn't need any tap gesture recognizers, just the pan gesture recognizer on each piece.  When the user finishes dragging the piece (i.e., pick their finger up off the screen), the piece should animate to the center of a square if it's intersecting an open space.  Otherwise, it should animate back to its starting point.

**Comment by tabinks** [comment]
Agreed.

**Comment by kbsrunschi** [comment]
Ok cool thanks, thats what I did :)

**Comment by kbsrunschi** [comment]
So my gesture isnt getting recognized, and I followed the steps in the slides/playground/Ray Wenderlich -- am I setting it to the wrong view and thats why its not picking it up?

**Comment by tabinks** [comment]
Gestures should be attached to the views: `myView.addGestureRecognizer()`.  Every X and O should have a gesture attached to them.

**Comment by susanstevens** [comment]
I pulled down your code, and it looks like the issue is that you're attaching the same gesture recognizer to both views.  Each view should have it's own gesture recognizer -- when you add the same recognizer to a second view, it invalidates the recognizer on the first view.

**Comment by kbsrunschi** [comment]
Ah ok I thought I made two, that would definitely be it! Thanks!

**Comment by kbsrunschi** [comment]
Ok so I gave each piece their own and still nothing.. I pushed my changes - any insight?

**Comment by susanstevens** [comment]
Looks like there's a typo on line 184 of your view controller.  You're setting `userInteractionEnabled` to false on `crossPiece`.

**Comment by kbsrunschi** [comment]
Oh doy, thanks! It works now :)
