### ISSUE TITLE
Swift Closures

### ISSUE THREAD

**Issue by susanstevens** [uchicago-mobi/2016-Summer-Forum#59]
The projects for homework 4 looked good for the most part, but I noticed some confusion around closures and multi-threading.  Here's an example of the kind of code that won't work exactly as you might expect.

```
    func handleRefresh(refreshControl: UIRefreshControl) {
        getIssues(urlString) { (issues) in
            // Nothing in here will be executed until AFTER the service call completes.
            self.issues = issues
            dispatch_async(dispatch_get_main_queue()) {
                self.tableView.reloadData()
            }
        }
        refreshControl.endRefreshing()  // WRONG: This line will be called too early.
    }
```

In the function signature for `getIssues`, there's a parameter called `completion` that is of type `([[String: AnyObject]]?) -> Void`, which is a function (or closure) that takes an optional array of dictionaries and returns nothing.  A common pattern when you're executing something on a background thread (such as a network call) is to pass in a closure with the code that you want to call once the background task completes.  The syntax is a little weird, but it's explained well [here](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/Closures.html).

In the code above, `getIssues` is called, which causes a network call to be kicked off on a background thread.  Execution on the main thread continues, and `refreshControl.endRefreshing()` is the next line after the `getIssues` closure, so it gets called right away, even before fresh data is returned from the service call.

Here's how to correct the code above.

```
    func handleRefresh(refreshControl: UIRefreshControl) {
        getIssues(urlString) { (issues) in
            self.issues = issues
            dispatch_async(dispatch_get_main_queue()) {
                self.tableView.reloadData()
                self.refreshControl?.endRefreshing() // CORRECT: The refresh control doesn't stop spinning until after the service call completes.
            }
        }
    }
```

Notice that `endRefreshing()` is called inside the `getIssues` completion block, which won't be executed until after the network call completes.  This guarantees that the refresh control will keep spinning until new data has been fetched (or the network call fails), instead of stopping right away.

**Comment by kbsrunschi** [comment]
UIRefreshControl is coming up as undeclared... was this changed/updated for the new Swift? (Googling leads to still using UIRefreshControl)

**Comment by kbsrunschi** [comment]
nvm looks like its because I put it in the singleton instead of the uiview
