### ISSUE TITLE
Office Hours 10:30-12:30 in Young

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2016-Summer-Forum#62]

**Comment by tabinks** [comment]
Wednesday.

**Comment by kbsrunschi** [comment]
The default of the project comes with a "Content View>Title" in Master Controller... but it wont let me resize the Title/add anything else/delete it... why is this locked and how do I unlock it to add another label?

**Comment by susanstevens** [comment]
If you select the cell and open the Attributes Inspector, you can change the cell's style to "Custom" instead of "Basic".  This will get rid of the title label and let you put whatever you want in there.

**Comment by kbsrunschi** [comment]
awesome thank you

**Comment by kbsrunschi** [comment]
Somehow I always have issues linking attributes to the classes. I set up a tableviewcell class that is a subclass of UITableViewCell to declare the new labels and they wont link... Im matching against FoodTracker and not seeing any differences in settings.
