### ISSUE TITLE
Question About Assignment Instructions

### ISSUE THREAD

**Issue by tjp36** [uchicago-mobi/2016-Summer-Forum#63]
In the "The View Controllers" portion of the instructions, the following is given in reference to the JSON returned by Duck Duck Go API:

"Use NSDateFormatter to display only the publishedDate field in MediumStyle"

However, the JSON returned by the Duck Duck Go API does not contain a field called MediumStyle or publishedDate.  What should we do about this?

Thanks

**Comment by susanstevens** [comment]
#61 You can ignore that.  It's from an older version of the assignment.
