### ISSUE TITLE
Updated Write-up

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2016-Summer-Forum#65]
I've been trying to update the write-up as questions come in to clarify issues that are arising.  There are no new requirements, the changes are only to help explain the assignment better.

**Comment by jvmakin** [comment]
This may be a dumb question, but where is the updated write-up? >_<

**Comment by tabinks** [comment]
On the website.  I just added/clarified to what was there.

**Comment by jvmakin** [comment]
Never mind. Found it.

**Comment by jvmakin** [comment]
Thanks!
