### ISSUE TITLE
Office Hours Saturday 10am-noon in Young 302

### ISSUE THREAD

**Issue by susanstevens** [uchicago-mobi/2016-Summer-Forum#68]
Usual time and place!

**Comment by kbsrunschi** [comment]
I have family in town this weekend - can I schedule time with you for Sunday evening? I need help getting the hang of layouts. Thank you

**Comment by susanstevens** [comment]
I should be available Sunday evening to answer some questions on the forum, but I don't think I can make it back down to Hyde Park.  I usually have some flexibility as to when I hold office hours on the weekends, though.  Let me know earlier in the week next time and I can try to move things around.

**Comment by kbsrunschi** [comment]
Will do - thanks. My bookmarks are overriding each other and Ive tried a few different things to store multiple values in the NSUser dictionary and array - but still only retrieving the most recent link, and that link is not being shown on the bookmarks page. Any ideas?

**Comment by kbsrunschi** [comment]
Can we meet before class tomorrow or after to review the layouts?

**Comment by kbsrunschi** [comment]
Also I have a function that checks internet connectivity, and I have validated it is returning "true" when internet is on and the method is completing, but its returning false in the main class... which makes no sense - its returning true but getting registered as false in the main class.

**Comment by susanstevens** [comment]
Sorry I wasn't able to be at class today.  Hopefully you were able to talk with Andrew, but let me know if you still have questions!

I'm not sure what's going on with the connectivity issue... I think Dana is grading your assignment this week, so I'll let her know to look at that.  She might be able to give you some pointers as to what was going on there.
