### ISSUE TITLE
Best practices for storing appearance values?

### ISSUE THREAD

**Issue by jbairUChicago** [uchicago-mobi/2016-Summer-Forum#69]
Are there best practices to centralize appearance information, to avoid hardcoding values in code or the storyboard? Is there something similar to CSS where you define rules based on the id, class, or tag of a control?

I’ve seen mentions of putting values in plists, and some contributions that appear to take a custom file and alter the storyboard. But I was wondering what you’ve seen and used based on experience.

This question is a good summary:

HTML has CSS styles e.g. class="styleName"
Windows8/XAML has static style resources e.g. Style="{StaticResource styleName}"
Android has style tags e.g. style="@style/styleName"
iOS has ???
http://stackoverflow.com/questions/18528625/ios-equivalent-to-a-stylesheet

**Comment by susanstevens** [comment]
Good question!  I would say UIAppearance is the closest you'll get if you're looking for a native solution.  This article is a good introduction: http://nshipster.com/uiappearance/.  It also lists some 3rd party frameworks that try to replicate the concept of a stylesheet more closely.

**Comment by tabinks** [comment]
Susan is correct that you should be looking to `UIAppearance` for this.  To emulate a 'stylesheet' you can do something as simple as a declaring constants or creating a class to store the color information (as Susan suggested).  Once you have all the color info centralized you can make changes that will be app-wide by changing in one place.  

To have a "dark" mode, you would just store additional colors for that mode and when necessary (eg tapping a dark mode button), load the colors form the secondary palette.

**Comment by jbairUChicago** [comment]
Before I close this, this is a useful example of "themes" via `UIAppearance` and AppDelegate. 

https://www.raywenderlich.com/108766/uiappearance-tutorial
