### ISSUE TITLE
Strange Warning regarding App Icons

### ISSUE THREAD

**Issue by tjp36** [uchicago-mobi/2016-Summer-Forum#70]
I keep getting a strange warnings when I compile my program:  "A 76x76 app icon is required for iPad apps targeting iOS 7.0 and later."

The reason this is odd is the app icon in this slot IS a 76 x 76 icon.  I got it from this website (http://www.gieson.com/Library/projects/utilities/icon_slayer/#.V5vBJZMrJsY) which should have (theoretically) provided me with all the icons I need.  All the other Icons I got from the site worked with no warning.

Has anyone else gotten this warning?

**Comment by susanstevens** [comment]
Strange!  I'll try generating some icons with that website and see if I get the same error.  Does it also happen if you create your own 76X76 icon?

**Comment by naietsg** [comment]
I did. Replacing it manually worked for me (i.e. 76 x 76 for 1x, 152 x 152 for 2x)

**Comment by tjp36** [comment]
Thanks will give this a try.
