### ISSUE TITLE
Message from Console when I Run a search...

### ISSUE THREAD

**Issue by tjp36** [uchicago-mobi/2016-Summer-Forum#72]
When I run a search, tap a cell to go to detail view, and then tap the back button to go back to the MasterView, I get the following message printed to the console:

`2016-07-30 20:34:28.630 DuckDuckGo[1830:48579594] Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.`

The app does not crash, and as far as I can tell, functionality is not affected by this.  Additionally, I only get this message once per search.  For example, if I go back to the MasterView, click on another result from the same search, load the page, and then tap "Back", the message does not appear.

Anyone have something similar happen or know how to fix it?  My googling has not turned up any clear answers yet on how to get this to go away.

**Comment by tabinks** [comment]
Are you pressing the back button really quickly before the web view has loaded? That error usually relates to win a few hasn't had sufficient time to be drawn on the screen and then a transition is triggered. Remember that the way most animations work are that the current view is saved as an image and then just that image is moved for the animation.

**Comment by tjp36** [comment]
No, the message is displayed even if I wait several minutes after the page is loaded.

**Comment by kbsrunschi** [comment]
I got that too - when a search only took up a couple cells and an old search still persisted and I clicked it
