### ISSUE TITLE
Assignment 7 Repo & Tips

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2016-Summer-Forum#77]
Repo: https://classroom.github.com/assignment-invitations/784854a6d2fa63892973cee0751af612

Sorry for the delay on the assignment write-up.  I will change the due date to August 9th at 5:29PM (1 extra day to account for this).

**Comment by tabinks** [comment]
# Cache

A major objective of this assignment is to begin to think about how to store and retrieve data with special considerations for networking.  Caching data should be an important part of your strategy.  

Here's some popular caching frameworks for inspiration (i.e. do not use these for your assignment):
- Haneke: https://github.com/Haneke/HanekeSwift
- SDWebImage: https://github.com/rs/SDWebImage
- FastImageCache: https://github.com/path/FastImageCache

**Comment by tabinks** [comment]
## App Transport Security

There is a new security feature in iOS9 that allows developers to specify which servers an app can request data from (i.e. whitelist).  Here is a post about it: http://useyourloaf.com/blog/app-transport-security/

There is a lot of information there, but the gist of it is that you need to add this statement to your Info.plist file.  

![](http://useyourloaf.com/assets/images/2015/2015-09-09-003.png)

You will need to add this to your Assignment 7 application.

**Comment by benvcarr** [comment]
FWIW, I also found that if you just make all the URLs https rather than http it all works fine as well (no whitelisting needed).
