### ISSUE TITLE
Getting error information up the chain from utility classes

### ISSUE THREAD

**Issue by jbairUChicago** [uchicago-mobi/2016-Summer-Forum#80]
This relates to the networking code used for both Github and DuckDuckGo. When you have the code to send and retrieve the response implemented in a utility class (a singleton in case of DuckDuckGo), is there a way to get the error detail up to the original caller?

For reference, the code

```
func getAnswers(url: String, completion:([[String: AnyObject]]?) -> Void) {

        // Download the issues
        // Pass back the array of dictionaries in the completion block
        //completion()
        guard let url = NSURL(string: url) else {
            fatalError("Unable to create NSURL from string")
        }

        // Create a vanilla url session
        let session = NSURLSession.sharedSession()

        // Create a data task
        let task = session.dataTaskWithURL(url, completionHandler: { (data, response, error) -> Void in

            // Print out the response
            //print("Response: \(response)")

            // Ensure there were no errors returned from the request
            guard error == nil else {
                print("error: \(error!.localizedDescription): \(error!.userInfo)")
                fatalError("Invalid response")
            }

            // Ensure there is data and unwrap it
            guard let data = data else {
                print("Error: Data is nil")
                fatalError("Data is nil")
            }

            // We received data but it needs to be processed
            //print("Raw data: \(data)")

```

We call completion to get the data up, but I can't seem to figure out how to pass the error up after reading through the slides. The only option without passing it up to the original caller/completion block is to invoke a UIAlert which seems sloppy for a networking class.

**Comment by jbairUChicago** [comment]
A better way to put this is, "we pass (answers) or (issues) back to the original function call. Can the error variable be passed and if so, how is it accessed syntactically?"

**Comment by tabinks** [comment]
There are many complicated solutions (mostly hacks) to `throw` from an async closure.  There is even syntax for `rethrow`.  Here a couple of solutions:
- http://ericasadun.com/2015/06/18/swift-asynchronous-error-handling/
- https://forums.developer.apple.com/thread/14429
- http://stackoverflow.com/questions/34957802/best-way-to-handle-errors-from-async-closures-in-swift-2

As you can see, they can become pretty complex.  For this assignment, if you want to use this in your networking class, you can handle errors outside of the async call.  Something like this:

``` swift
func getAnswers(url: String, completion:([[String: AnyObject]]?) throws -> Void) {
       guard let url = NSURL(string: url) else {
           // throw error here
        }

      // Test network connection (synchronously)
     if noNetwork {
        // throw error here
    }

   // Don't worry about throwing errors from here
  // You will learn about the errors from the `error` variable
  // in the completion handler

  let session = NSURLSession.sharedSession()
  let task = session.dataTaskWithURL(url, completionHandler: { (data, response, error) -> Void in 
// ...
}
```
