### ISSUE TITLE
Confusion About NSCache

### ISSUE THREAD

**Issue by tjp36** [uchicago-mobi/2016-Summer-Forum#81]
I am confused over the instructions regarding Data/NSCache.  The instructions state:

> Images should be stored using NSCache. Use the images url as the key. When showing an image in the collection view, first try to load the image from the cache, if it is not there retrieve it from the network. After successfully downloading the image, save it to NSCache so it will be available later.

These instructions seem to imply that NSCache is being used to save Images to disk.  However, It is my understanding that NSCache does not persist between launches (http://stackoverflow.com/questions/13497678/does-nscache-persist-between-launches).  Is this correct?  If it is, I don't see how the instructions to "first try to load the image from the cache" make much sense because:

1)  Since NSCache does not persist, each time we launch the application it will download all images from our personal URL
2) As I read it the instructions don't provide for any other time when we would need to check for images after launch.

How can we load an image from something that is reset each time the application is run?  Should we be storing the images elsewhere on disk and loading from there?  Or maybe are we required to have some sort of pull to refresh control (this is not currently in the instructions as far as I can tell) that would make using the NSCache worthwhile?

Any clarification you could provide would be appreciated.

Thanks

**Comment by tabinks** [comment]
The behavior of `NSCache` can be a bit confusing.  Remember that your application will not "launch" as frequently as it might seem.  The most common behavior is that it will move to the foreground from suspended state.  In this scenario, `NSCache` will persist between this transition.

`NSCache` does not persist to disk, it only keeps objects in memory.  This makes it fast, but, under certain circumstances, it can be rather short-lived.  A more robust caching strategy would probably include saving to disk (most likely in the `/Library/Cache/` directory.  The advantage, in our application, is that by using `NSCache` and not writing/reading from files we do not have the overhead of reading the images from disk.

**Comment by tjp36** [comment]
So is it a requirement of the project to use save to Library/Cache in addition to using the NSCache?

**Comment by tabinks** [comment]
No.  Just use `NSCache` for the assignment.
