### ISSUE TITLE
Error returned on image upload attempt

### ISSUE THREAD

**Issue by hiesenburg88** [uchicago-mobi/2016-Summer-Forum#82]
I've been able to successfully upload one image from my app, but now I'm getting back this error from the app engine server. I'm not sure what to make of it. Any suggestions?

Optional(<NSHTTPURLResponse: 0x7f92b2e90bf0> { URL: https://stachesandglasses.appspot.com/post/mhmcdonald/ } { status code: 500, headers {
    "Cache-Control" = "no-cache";
    "Content-Length" = 3974;
    "Content-Type" = "text/html; charset=utf-8";
    Date = "Thu, 04 Aug 2016 15:17:07 GMT";
    Server = "Google Frontend";
    "alt-svc" = "quic=\":443\"; ma=2592000; v=\"36,35,34,33,32,31,30\"";
    "alternate-protocol" = "443:quic";
    "x-cloud-trace-context" = "c4bb903c4358d4ac91230fee7334ac51;o=1";
} })
nil
Optional(<html>
  <head>
    <title>Internal Server Error</title>
    <style>
      body {
        padding: 20px;
        font-family: arial, sans-serif;
        font-size: 14px;
      }
      pre {
        background: #F2F2F2;
        padding: 10px;
      }
    </style>
  </head>
  <body>
    <h1>Internal Server Error</h1>
    <p>The server has either erred or is incapable of performing
    the requested operation.</p>
    <pre>Traceback (most recent call last):
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py&quot;, line 1535, in **call**
    rv = self.handle_exception(request, response, e)
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py&quot;, line 1529, in **call**
    rv = self.router.dispatch(request, response)
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py&quot;, line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py&quot;, line 1102, in **call**
    return handler.dispatch()
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py&quot;, line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py&quot;, line 570, in dispatch
    return method(_args, *_kwargs)
  File &quot;/base/data/home/apps/s~stachesandglasses/1.367183277548328076/main.py&quot;, line 107, in post
    photo.put()
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/model.py&quot;, line 3451, in _put
    return self._put_async(**ctx_options).get_result()
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py&quot;, line 383, in get_result
    self.check_success()
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py&quot;, line 427, in _help_tasklet_along
    value = gen.throw(exc.__class__, exc, tb)
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/context.py&quot;, line 824, in put
    key = yield self._put_batcher.add(entity, options)
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py&quot;, line 427, in _help_tasklet_along
    value = gen.throw(exc.__class__, exc, tb)
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/context.py&quot;, line 358, in _put_tasklet
    keys = yield self._conn.async_put(options, datastore_entities)
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py&quot;, line 513, in _on_rpc_completion
    result = rpc.get_result()
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py&quot;, line 613, in get_result
    return self.__get_result_hook(self)
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py&quot;, line 1881, in __put_hook
    self.check_rpc_success(rpc)
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py&quot;, line 1371, in check_rpc_success
    rpc.check_success()
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py&quot;, line 579, in check_success
    self.__rpc.CheckSuccess()
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_rpc.py&quot;, line 134, in CheckSuccess
    raise self.exception
RequestTooLargeError: The request to API call datastore_v3.Put() was too large.

**Comment by hiesenburg88** [comment]
Update: I was able to get a second image to upload, but that was after about 30 minutes of waiting. I didn't change anything in my code related to the upload. Then I tried again in hopes of uploading a 3rd image, but it failed with the same error above.

**Comment by tabinks** [comment]
Did you try with a smaller image? I don't know exactly what that error is, but that seems like maybe the issue.

**Comment by hiesenburg88** [comment]
I've gotten 13 images uploaded successfully. But yes, this error keeps happening and it seems a bit sporadic. I've gotten images that have failed on one attempt to upload on another, which leads me to think that it doesn't have to do with the size of the image. Not sure what to make of it. Anyways, I'll close the ticket since it seems to be caused by the app engine and not my app.
