### ISSUE TITLE
Testing New Image Uploads from Camera

### ISSUE THREAD

**Issue by hiesenburg88** [uchicago-mobi/2016-Summer-Forum#83]
We're supposed to allow the user to be able to upload an image not just from the camera roll, but they're supposed to be able to take a picture and upload it. This functionality cannot be mimicked from the simulator because there is no camera. 

I think my code is working, but the only way to know is to put it on a device and test. Is this something that will be checked during the grading? I don't currently have a developer account setup to go through with this, but I'll go ahead if it's expected.

**Comment by tabinks** [comment]
If you have an iOS device you can load your application onto it without  A paid developer account.

if you don't have a device,  I would try to borrow one from someone. You will be really surprised it's performance difference between the simulator and actually running nice. As far as grading,  do your best to ensure that the camera code actually works. We will definitely tested using the simulator, but if you weren't able to test it on a device please leave a note in the README.

**Comment by tabinks** [comment]
Device....not nice.....Siri

**Comment by jbairUChicago** [comment]
@tabinks, for XCode 7, are you aware if you can run multiple custom apps without a paid Developer account?

I've been unsuccessful in this, only being able to run the most recently deployed app to the device.
