### ISSUE TITLE
Image is nil when segueing to Detail Controller

### ISSUE THREAD

**Issue by kbsrunschi** [uchicago-mobi/2016-Summer-Forum#87]
Ive tried using both the selectedImageCell.imageView.image and redo-ing the downloading of the image, but the imageDetailViewController.largeImageView.image is throwing a nil when I can see its being set with correct data -  any insight to what Im missing (see latest commit)? 

Thank you!

**Comment by susanstevens** [comment]
If you're setting it in prepareForSegue, the imageView may not have been initialized from storyboard yet. Try setting a property on the detail view controller to store the image and then setting the imageView's image in viewWillAppear. The imageView will no longer be nil at that point.

**Comment by kbsrunschi** [comment]
setting it in the main controller or the detail view controller? INitialize it (ie =ImageView()) or set it to a dummy value? or other? I initialized it with a frame in DetailViewController but still nothing

**Comment by kbsrunschi** [comment]
Looks like it was because I was setting an IBOutlet and needed to set a local var and then set it to the IBOutlet var... Im not in the DetailViewController and getting nils there.. Ill keep researching :)

**Comment by kbsrunschi** [comment]
All fixed :) Cant initialize the uiimageview when its an iboutlet
