### ISSUE TITLE
OverQuotaError

### ISSUE THREAD

**Issue by naietsg** [uchicago-mobi/2016-Summer-Forum#94]
Anyone else getting this error with AppEngine (and figure out a workaround)? I was able to pull data for a short period earlier today, but otherwise have been locked out for awhile now. 

![unnamed](https://cloud.githubusercontent.com/assets/8528766/17637108/0bbf5b94-60a7-11e6-9621-2f1b1a9c727f.png)

**Comment by kbsrunschi** [comment]
Probably over your quota of a free allowance? A lot of companies who give their APIs out have a limit on how much you can call them per day while you're getting it for free.

**Comment by susanstevens** [comment]
That would be my guess as well.  Try it again today and see if you're getting the same error.

**Comment by tabinks** [comment]
I would also add that this is the first time we had a quota issue, even the day before the assignment was due.  I would suspect that there is something inefficient going on in your code related to networking (ie. you're hitting the server too many times).
