### ISSUE TITLE
Has anyone had any issues with the new "rootless" feature of El Capitan (10.11)?

### ISSUE THREAD

**Issue by jbairUChicago** [uchicago-mobi/2016-Summer-Forum#97]
I noticed that there was a copy of the cocoapods binary in /usr/bin. When I went to update the gem (with sudo and then su) I got a permission denied error. 

Apparently many directories are now locked down with a feature called System Integrity Protection. 

Apparently it can be disabled with sudo nvram boot-args="rootless=0"and the instantaneous reboot  that is performed, but I'm wondering if anyone has left it in place and used an alternative other than forcing an install directory of /usr/local/bin (actually writable as a sudoer) with the gem command.

**Comment by tabinks** [comment]
I haven't had problems with this.  I don't remember doing anything special when I upgraded to el capitan.

**Comment by jbairUChicago** [comment]
What do you get from the Console  for these 2 commands?

`which pod`

`pod --version`

**Comment by tabinks** [comment]
I haven't run cocoa pods since updating to El Capitan.  I found this which seems to have many different solutions.

https://github.com/CocoaPods/CocoaPods/issues/3680

**Comment by jbairUChicago** [comment]
Good find. It seems adding -n /usr/local/bin is the way to go.

**Comment by naietsg** [comment]
sudo gem install -n /usr/local/bin cocoapods 
- Create workspace and project
- Open terminal and change directory to your workspace
- Create pod file by running `pod init`
- Edit this file with the pods you want by finding the pod names on https://cocoapods.org/
- Run `pod install` to actually download pods.

Open project and your pods will be added.

**Comment by jbairUChicago** [comment]
I made a mistake while typing that out that last line: Open the workspace (not the project).
